"""ChefAIService (T131, T132, T133)

Phase 9: Conversational Chef AI — Halal filter, chat loop, and fridge logic matching.

Architecture:
  - Halal filter: deterministic Python blocklist-first (T131), applied BOTH to
    incoming user query AND outgoing AI response (double-guard pattern).
  - Chat (T132): Sends conversation history to gpt-4o-mini, persists session to
    Neon Postgres chef_ai_sessions table, returns ChefAIChatResponse.
  - Fridge Logic (T133): Fetches all active recipes from DB, compares ingredient
    name overlap against user inventory, returns ranked RecipeSuggestion list.

Design constraints:
  - NO frontend imports.
  - NO modifications to recipe_service.py or any Phase 8 components.
  - All DB writes use the asyncpg pool (same pattern as RecipeService).
"""
import json
import re
from typing import List, Optional, Dict, Any
from uuid import UUID, uuid4
from datetime import datetime, timezone

import asyncpg
from openai import AsyncOpenAI

from src.config import OPENAI_API_KEY
from src.data.substitutions import (
    HALAL_BLOCKLIST,
    get_substitution,
    get_halal_safe_alternatives,
    search_substitutions,
    is_halal_blocked,
)
from src.models.chef_ai import (
    ChefAIChatRequest,
    ChefAIChatResponse,
    ChefAICitation,
    ChefAIMessage,
    ChefAISession,
    FridgeIngredient,
    FridgeLogicRequest,
    FridgeLogicResponse,
    RecipeSuggestion,
    DietaryRestriction,
)
from src.models.recipe import LanguageCode
from src.services.rag_service import RAGService
from src.utils.logger import get_logger

logger = get_logger(__name__)

# Model configured per Phase 9 architectural decisions
CHEF_AI_MODEL = "gpt-4o-mini"
CHEF_AI_MAX_TOKENS = 512
CHEF_AI_TEMPERATURE = 0.7


class HalalViolationError(Exception):
    """Raised when a query or response violates Halal compliance rules."""
    pass


class ChefAIService:
    """Conversational Chef AI service.

    Provides core logic for the multilingual Conversational Chef assistant, including:
      - Deterministic pre-flight and post-flight Halal compliance filtering.
      - Session management and persistence in Neon PostgreSQL.
      - Context integration using RAG and vector database lookups.
      - Fridge-logic recipe suggestions based on ingredients overlap.
      - Fast local ingredient substitution resolution.
    """

    def __init__(self, db_pool: asyncpg.Pool):
        """Initializes ChefAIService with active database and client backends.

        Args:
            db_pool (asyncpg.Pool): Database connection pool for storing session histories.
        """
        self.db_pool = db_pool
        self.openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)
        self.rag_service = RAGService(db_pool)

    # ─────────────────────────────────────────────────────────────────────────
    # T131: Halal Filter — deterministic blocklist enforcement
    # ─────────────────────────────────────────────────────────────────────────

    def _check_halal_compliance(self, text: str) -> List[str]:
        """Scans the text for any blocked ingredients or haram terms from the HALAL_BLOCKLIST.

        Matches whole-word boundaries only to avoid false positive triggers.

        Args:
            text (str): Input text or response string to validate.

        Returns:
            List[str]: List of detected violating terms. If empty, the text is compliant.
        """
        violations = []
        text_lower = text.lower()
        for blocked in HALAL_BLOCKLIST:
            # Match whole-word occurrences only
            pattern = r'\b' + re.escape(blocked) + r'\b'
            if re.search(pattern, text_lower):
                violations.append(blocked)
        return violations

    def _sanitize_query(self, message: str) -> tuple[str, bool, List[str]]:
        """Pre-flight check executing inspection on user queries before model ingestion.

        Args:
            message (str): Raw user query string.

        Returns:
            tuple[str, bool, List[str]]:
                - message: The query message.
                - is_halal_concern: True if violations were detected.
                - violations: List of matching blocked terms.
        """
        violations = self._check_halal_compliance(message)
        return message, bool(violations), violations

    def _validate_ai_response(self, response_text: str) -> tuple[str, bool]:
        """Post-flight validation check on LLM generated responses.

        If any blocked ingredient is detected, it logs the violation and redirects the response
        by replacing the raw output with a clean, helpful suggestion of Halal alternatives.

        Args:
            response_text (str): The raw response string generated by OpenAI.

        Returns:
            tuple[str, bool]:
                - response: The safe sanitized message.
                - is_compliant: True if the response was clean, False if it was intercepted.
        """
        violations = self._check_halal_compliance(response_text)
        if violations:
            logger.warning(
                f"⚠️ Halal post-flight violation detected in AI response. "
                f"Blocked terms: {violations}. Replacing with safe fallback."
            )
            # Build safe fallback using substitution DB
            fallback_parts = [
                "I'd suggest a Halal-friendly alternative for this recipe. "
            ]
            for v in violations[:2]:  # Show alternatives for first 2 violations max
                alts = get_halal_safe_alternatives(v)
                if alts:
                    best = alts[0]
                    fallback_parts.append(
                        f"Instead of {v}, try **{best['name']}** ({best['ratio']}). "
                        f"{best.get('note', '')}"
                    )
            return " ".join(fallback_parts).strip(), False
        return response_text, True

    # ─────────────────────────────────────────────────────────────────────────
    # Session persistence helpers
    # ─────────────────────────────────────────────────────────────────────────

    async def _load_session(self, session_id: UUID) -> Optional[ChefAISession]:
        """Loads session state details from Neon Postgres.

        Args:
            session_id (UUID): Unique session ID.

        Returns:
            Optional[ChefAISession]: The parsed session object, or None if not found.
        """
        async with self.db_pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT session_id, user_id, conversation_history,
                       user_inventory, dietary_restrictions, created_at, updated_at
                FROM chef_ai_sessions
                WHERE session_id = $1
                """,
                session_id,
            )
            if not row:
                return None
            return ChefAISession(
                session_id=row["session_id"],
                user_id=row["user_id"],
                conversation_history=json.loads(row["conversation_history"] or "[]"),
                user_inventory=json.loads(row["user_inventory"] or "[]"),
                dietary_restrictions=json.loads(row["dietary_restrictions"] or "[]"),
                created_at=row["created_at"],
                updated_at=row["updated_at"],
            )

    async def _save_session(self, session: ChefAISession) -> None:
        """Saves or updates a Chef AI session in Neon Postgres.

        Args:
            session (ChefAISession): Session instance containing chat histories and parameters.
        """
        history_json = json.dumps([
            {
                "role": m.role,
                "content": m.content,
                "timestamp": m.timestamp.isoformat(),
            }
            for m in session.conversation_history
        ])
        inventory_json = json.dumps([
            {"name": i.name, "quantity": i.quantity}
            for i in session.user_inventory
        ])
        restrictions_json = json.dumps([r.value for r in session.dietary_restrictions])

        async with self.db_pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO chef_ai_sessions
                    (session_id, user_id, conversation_history, user_inventory,
                     dietary_restrictions, created_at, updated_at)
                VALUES ($1, $2, $3::jsonb, $4::jsonb, $5::jsonb, $6, $7)
                ON CONFLICT (session_id) DO UPDATE SET
                    conversation_history = EXCLUDED.conversation_history,
                    user_inventory       = EXCLUDED.user_inventory,
                    dietary_restrictions = EXCLUDED.dietary_restrictions,
                    updated_at           = EXCLUDED.updated_at
                """,
                session.session_id,
                session.user_id,
                history_json,
                inventory_json,
                restrictions_json,
                session.created_at,
                datetime.now(timezone.utc),
            )

    # ─────────────────────────────────────────────────────────────────────────
    # T132: ChefAIService.chat()
    # ─────────────────────────────────────────────────────────────────────────

    async def chat(self, request: ChefAIChatRequest) -> ChefAIChatResponse:
        """Processes a chat turn with the Conversational Chef.

        Flow:
          1. Verifies input query for Halal violations.
          2. Runs a fast local match for direct substitution shortcuts.
          3. Checks if session is active or creates a new one.
          4. Fetches recipe vector database RAG context.
          5. Generates system prompt enforcing dietary restrictions and context.
          6. Submits RAG prompt + chat history context to gpt-4o-mini.
          7. Runs post-flight compliance checks on model output.
          8. Saves conversation progress state and returns results.

        Args:
            request (ChefAIChatRequest): Request payload details.

        Returns:
            ChefAIChatResponse: Output reply containing results metadata.
        """
        session_id = request.session_id or uuid4()
        logger.info(f"Chef AI chat — session={session_id}, user={request.user_id}")

        # ── Step 1: Pre-flight Halal check ───────────────────────────────────
        _, has_halal_concern, violations = self._sanitize_query(request.message)
        if has_halal_concern:
            logger.info(f"Halal concern in query: {violations}. Will redirect via system prompt.")

        # ── Step 2: Local substitution shortcut ──────────────────────────────
        substitution_shortcut = self._try_substitution_shortcut(request.message)
        if substitution_shortcut:
            logger.info("Substitution shortcut hit — skipping LLM call.")
            return ChefAIChatResponse(
                session_id=session_id,
                reply=substitution_shortcut,
                is_halal_compliant=True,
                citations=[],
                suggested_recipe_ids=[],
                tokens_used=0,
            )

        # ── Step 3: Load or create session ───────────────────────────────────
        session = await self._load_session(session_id)
        if not session:
            session = ChefAISession(
                session_id=session_id,
                user_id=request.user_id,
                dietary_restrictions=request.dietary_restrictions,
                user_inventory=[],
            )

        # Merge incoming history (client may have newer turns than DB)
        if request.conversation_history:
            session.conversation_history = request.conversation_history[-10:]

        # ── Step 4: Fetch RAG context ─────────────────────────────────────────
        rag_context = await self.rag_service.get_chef_ai_rag_context(
            query=request.message,
            language=LanguageCode.EN,
            recipe_context_id=request.recipe_context_id,
        )

        # ── Step 5: Build system prompt ───────────────────────────────────────
        restrictions = request.dietary_restrictions or session.dietary_restrictions
        # Always enforce Halal
        if DietaryRestriction.HALAL not in restrictions:
            restrictions = [DietaryRestriction.HALAL] + list(restrictions)

        system_prompt = self.rag_service.build_chef_ai_system_prompt(
            user_inventory=session.user_inventory or None,
            dietary_restrictions=restrictions,
            recipe_context=rag_context or None,
        )

        # ── Step 6: Build message list for OpenAI ────────────────────────────
        messages: List[Dict[str, str]] = [{"role": "system", "content": system_prompt}]

        # Prior conversation turns
        for turn in session.conversation_history[-8:]:  # Keep last 8 turns as context
            messages.append({"role": turn.role, "content": turn.content})

        # Current user message
        messages.append({"role": "user", "content": request.message})

        # ── Step 7: Call gpt-4o-mini ──────────────────────────────────────────
        try:
            completion = await self.openai_client.chat.completions.create(
                model=CHEF_AI_MODEL,
                messages=messages,
                max_tokens=CHEF_AI_MAX_TOKENS,
                temperature=CHEF_AI_TEMPERATURE,
            )
            raw_reply = completion.choices[0].message.content or ""
            tokens_used = completion.usage.total_tokens if completion.usage else None

        except Exception as e:
            logger.error(f"OpenAI API error in Chef AI chat: {e}")
            raw_reply = (
                "I'm having trouble connecting to my knowledge base right now. "
                "Please try again in a moment."
            )
            tokens_used = None

        # ── Step 8: Post-flight Halal guard ──────────────────────────────────
        final_reply, was_response_safe = self._validate_ai_response(raw_reply)

        # ── Step 9: Build citations for food safety claims ───────────────────
        citations = self._extract_citations(final_reply)

        # ── Step 10: Persist updated session ─────────────────────────────────
        session.conversation_history.append(
            ChefAIMessage(role="user", content=request.message)
        )
        session.conversation_history.append(
            ChefAIMessage(role="assistant", content=final_reply)
        )
        # Trim to last 10 turns
        session.conversation_history = session.conversation_history[-10:]

        try:
            await self._save_session(session)
        except Exception as e:
            logger.warning(f"Failed to persist Chef AI session {session_id}: {e}")

        logger.info(
            f"Chef AI reply — session={session_id}, "
            f"tokens={tokens_used}, halal_safe={was_response_safe}"
        )

        return ChefAIChatResponse(
            session_id=session_id,
            reply=final_reply,
            is_halal_compliant=was_response_safe,
            citations=citations,
            suggested_recipe_ids=[],
            tokens_used=tokens_used,
        )

    async def chat_stream(self, request: ChefAIChatRequest):
        """Asynchronous generator for streaming Chef AI responses via SSE (T176).

        Flow:
          1. Loads or creates conversation session.
          2. Fetches RAG context from Qdrant vector database.
          3. Generates system prompt enforcing dietary restrictions.
          4. Submits prompt + chat history context to OpenAI chat completions with stream=True.
          5. Yields chunks as Server-Sent Events (SSE) in standard 'data: ...' format.
          6. Post-flight validation checks the complete generated text and persists history.
        """
        session_id = request.session_id or uuid4()
        logger.info(f"Chef AI chat stream — session={session_id}, user={request.user_id}")

        # Load or create session
        session = await self._load_session(session_id)
        if not session:
            session = ChefAISession(
                session_id=session_id,
                user_id=request.user_id,
                dietary_restrictions=request.dietary_restrictions,
                user_inventory=[],
            )

        # Merge incoming history
        if request.conversation_history:
            session.conversation_history = request.conversation_history[-10:]

        # Fetch RAG context from Qdrant vector DB
        rag_context = await self.rag_service.get_chef_ai_rag_context(
            query=request.message,
            language=LanguageCode.EN,
            recipe_context_id=request.recipe_context_id,
        )

        # Build system prompt enforcing dietary restrictions (always includes Halal blocklist)
        restrictions = request.dietary_restrictions or session.dietary_restrictions
        if DietaryRestriction.HALAL not in restrictions:
            restrictions = [DietaryRestriction.HALAL] + list(restrictions)

        system_prompt = self.rag_service.build_chef_ai_system_prompt(
            user_inventory=session.user_inventory or None,
            dietary_restrictions=restrictions,
            recipe_context=rag_context or None,
        )

        # Build message list for OpenAI
        messages: List[Dict[str, str]] = [{"role": "system", "content": system_prompt}]
        for turn in session.conversation_history[-8:]:
            messages.append({"role": turn.role, "content": turn.content})
        messages.append({"role": "user", "content": request.message})

        full_reply_chunks = []
        try:
            stream = await self.openai_client.chat.completions.create(
                model=CHEF_AI_MODEL,
                messages=messages,
                max_tokens=CHEF_AI_MAX_TOKENS,
                temperature=CHEF_AI_TEMPERATURE,
                stream=True,
            )
            async for chunk in stream:
                content = chunk.choices[0].delta.content or ""
                if content:
                    full_reply_chunks.append(content)
                    # Yield formatted as Server-Sent Event (SSE)
                    yield f"data: {content}\n\n"
                    
            # Complete raw output post-flight validation
            full_reply = "".join(full_reply_chunks)
            final_reply, was_response_safe = self._validate_ai_response(full_reply)
            
            # Persist safety-sanitized turn in conversation history
            session.conversation_history.append(
                ChefAIMessage(role="user", content=request.message)
            )
            session.conversation_history.append(
                ChefAIMessage(role="assistant", content=final_reply)
            )
            session.conversation_history = session.conversation_history[-10:]
            await self._save_session(session)
            
        except Exception as e:
            logger.error(f"OpenAI API connection error in Chef AI stream: {e}")
            # Gracefully notify client of stream failure via standard SSE error structure
            yield f"data: {json.dumps({'error': 'Stream connection error', 'detail': str(e)})}\n\n"

    def _try_substitution_shortcut(self, message: str) -> Optional[str]:
        """Tries to intercept query with direct offline substitutions before calling LLM.

        Detects patterns asking for replacements and generates response from data.

        Args:
            message (str): User message.

        Returns:
            Optional[str]: Formatted markdown response of substitutions, or None if LLM is needed.
        """
        message_lower = message.lower()

        # Detect substitution intent patterns
        sub_patterns = [
            r"substitute(?:\s+for)?\s+([a-z\s]+?)(?:\?|$|\.)",
            r"replace(?:\s+the)?\s+([a-z\s]+?)(?:\s+with|\?|$|\.)",
            r"instead of\s+([a-z\s]+?)(?:\?|$|\.)",
            r"alternative(?:\s+to)?\s+([a-z\s]+?)(?:\?|$|\.)",
            r"don't have\s+([a-z\s]+?)(?:\s+on hand|\?|$|\.)",
            r"out of\s+([a-z\s]+?)(?:\?|$|\.)",
            r"no\s+([a-z\s]+?)\s+(?:on hand|available|\?|$|\.)",
        ]

        for pattern in sub_patterns:
            match = re.search(pattern, message_lower)
            if match:
                ingredient = match.group(1).strip()
                entry = get_substitution(ingredient)
                if entry:
                    # Halal-concern ingredient → lead with that
                    if entry.halal_concern:
                        lines = [
                            f"**{ingredient.title()}** is not Halal-permissible. "
                            f"Here are the best Halal-certified alternatives:\n"
                        ]
                    else:
                        lines = [f"**Substitutes for {ingredient.title()}:**\n"]

                    for alt in entry.alternatives[:4]:
                        lines.append(f"• **{alt['name']}** — {alt['ratio']}")
                        if alt.get("note"):
                            lines.append(f"  _{alt['note']}_")

                    return "\n".join(lines)

        return None  # No shortcut available — use LLM

    def _extract_citations(self, text: str) -> List[ChefAICitation]:
        """Extracts standard food safety citations based on keywords in model output text.

        Args:
            text (str): AI output text to inspect.

        Returns:
            List[ChefAICitation]: Structured list of citations indicating references.
        """
        citations = []
        citation_map = {
            "usda": ChefAICitation(
                text="USDA Food Safety and Inspection Service",
                url="https://www.fsis.usda.gov/food-safety"
            ),
            "fda": ChefAICitation(
                text="U.S. Food and Drug Administration",
                url="https://www.fda.gov/food"
            ),
            "who": ChefAICitation(
                text="World Health Organization — Food Safety",
                url="https://www.who.int/health-topics/food-safety"
            ),
            "halal": ChefAICitation(
                text="Islamic Food and Nutrition Council of America (IFANCA)",
                url="https://www.ifanca.org"
            ),
        }
        text_lower = text.lower()
        for keyword, citation in citation_map.items():
            if keyword in text_lower and citation not in citations:
                citations.append(citation)
        return citations

    # ─────────────────────────────────────────────────────────────────────────
    # T133: ChefAIService.get_fridge_logic_suggestions()
    # ─────────────────────────────────────────────────────────────────────────

    async def get_fridge_logic_suggestions(
        self, request: FridgeLogicRequest
    ) -> FridgeLogicResponse:
        """Evaluates recipes inside database to match user available ingredients (T133).

        Scores recipes using Jaccard Similarity on active items, automatically 
        excluding any recipe with Halal-violating ingredients.

        Args:
            request (FridgeLogicRequest): Input payload containing available ingredients,
                limits, and preferences.

        Returns:
            FridgeLogicResponse: List of suggestions and match statistics.
        """
        logger.info(
            f"Fridge logic — user={request.user_id}, "
            f"ingredients={[i.name for i in request.available_ingredients]}"
        )

        # Always enforce Halal
        restrictions = list(request.dietary_restrictions)
        if DietaryRestriction.HALAL not in restrictions:
            restrictions.append(DietaryRestriction.HALAL)

        # ── Normalize user inventory to lowercase set ─────────────────────────
        user_ingredients: set = {
            ing.name.lower().strip() for ing in request.available_ingredients
        }

        # ── Fetch all active recipes with ingredients from DB ─────────────────
        async with self.db_pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT
                    r.recipe_id,
                    r.name,
                    r.origin_country,
                    r.difficulty,
                    rt.ingredients
                FROM recipes r
                LEFT JOIN recipe_translations rt
                    ON r.recipe_id = rt.recipe_id AND rt.language_code = 'EN'
                WHERE r.is_active = true
                """
            )

        total_checked = len(rows)
        suggestions: List[RecipeSuggestion] = []

        for row in rows:
            recipe_id = row["recipe_id"]
            recipe_name = row["name"]
            origin = row["origin_country"]
            difficulty = row["difficulty"]

            # Parse ingredients JSONB
            raw_ingredients = row["ingredients"]
            ingredients_data = {}
            if isinstance(raw_ingredients, str):
                try:
                    ingredients_data = json.loads(raw_ingredients)
                except (json.JSONDecodeError, TypeError):
                    ingredients_data = {}
            elif isinstance(raw_ingredients, (dict, list)):
                ingredients_data = raw_ingredients

            # Extract ingredient names as a normalized set
            recipe_ingredient_names: set = set()
            if isinstance(ingredients_data, dict):
                for name in ingredients_data.keys():
                    if isinstance(name, str):
                        recipe_ingredient_names.add(name.lower().strip())
            elif isinstance(ingredients_data, list):
                for ing in ingredients_data:
                    if isinstance(ing, dict):
                        name = ing.get("name", "")
                        if isinstance(name, str) and name:
                            recipe_ingredient_names.add(name.lower().strip())
                    elif isinstance(ing, str):
                        recipe_ingredient_names.add(ing.lower().strip())

            if not recipe_ingredient_names:
                continue

            # ── Halal guard: skip if recipe contains blocked ingredients ──────
            blocked_found = any(
                is_halal_blocked(ing) for ing in recipe_ingredient_names
            )
            if blocked_found:
                logger.debug(f"Skipping recipe '{recipe_name}' — contains Halal-blocked ingredient")
                continue

            # ── Compute match score ───────────────────────────────────────────
            # Partial match: also check if user ingredient is contained in recipe ingredient name
            matched: set = set()
            for user_ing in user_ingredients:
                for recipe_ing in recipe_ingredient_names:
                    if user_ing in recipe_ing or recipe_ing in user_ing:
                        matched.add(recipe_ing)
                        break

            if not matched:
                continue  # No overlap — skip this recipe

            score = len(matched) / len(recipe_ingredient_names)
            missing = sorted(recipe_ingredient_names - matched)

            suggestions.append(
                RecipeSuggestion(
                    recipe_id=recipe_id,
                    name=recipe_name,
                    origin_country=origin,
                    difficulty=difficulty,
                    match_score=round(score, 3),
                    matched_ingredients=sorted(matched),
                    missing_ingredients=missing,
                )
            )

        # Sort by match score descending
        suggestions.sort(key=lambda s: s.match_score, reverse=True)

        # Limit to max_results
        suggestions = suggestions[: request.max_results]

        logger.info(
            f"Fridge logic — checked {total_checked} recipes, "
            f"returning {len(suggestions)} suggestions"
        )

        return FridgeLogicResponse(
            suggestions=suggestions,
            total_recipes_checked=total_checked,
        )
