"""chef_ai_sessions migration

Phase 9: Conversational Chef AI — chat session persistence.

Stores:
  - session_id (PK, UUID)
  - user_id (FK → users.id, nullable for anonymous use)
  - conversation_history (JSONB): array of {role, content, timestamp}
  - user_inventory (JSONB): array of {name, quantity} from fridge-logic
  - dietary_restrictions (JSONB): array of restriction strings
  - created_at, updated_at

Design decisions:
  - Nullable user_id supports anonymous Chef AI sessions (no login required)
  - JSONB for history/inventory avoids schema churn as the conversation format evolves
  - CASCADE delete on user_id: removing a user clears their Chef AI history
  - No FK to recipes table; recipe_context_id is stored inside conversation_history
    as part of message metadata, keeping schema decoupled from recipe schema.

Revision ID: a1b2c3d4e5f6
Revises: 26debdcf7ce8
Create Date: 2026-06-22 12:22:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB
import uuid

revision = 'a1b2c3d4e5f6'
down_revision = '26debdcf7ce8'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'chef_ai_sessions',

        # Primary key — UUID generated server-side
        sa.Column(
            'session_id',
            UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text('gen_random_uuid()'),
            comment='Unique session identifier, auto-generated by Postgres'
        ),

        # Optional link to authenticated user; NULL for anonymous sessions
        sa.Column(
            'user_id',
            UUID(as_uuid=True),
            sa.ForeignKey('users.id', ondelete='CASCADE'),
            nullable=True,
            comment='FK to users.id — NULL for anonymous Chef AI sessions'
        ),

        # Conversation history: array of {role, content, timestamp}
        sa.Column(
            'conversation_history',
            JSONB,
            nullable=False,
            server_default='[]',
            comment='Array of {role: user|assistant, content: str, timestamp: ISO8601}'
        ),

        # Fridge inventory snapshot for fridge-logic queries
        sa.Column(
            'user_inventory',
            JSONB,
            nullable=False,
            server_default='[]',
            comment='Array of {name: str, quantity: str|null} — last submitted fridge contents'
        ),

        # Dietary restrictions for Halal compliance enforcement
        sa.Column(
            'dietary_restrictions',
            JSONB,
            nullable=False,
            server_default='[]',
            comment='Array of restriction strings, e.g. ["halal", "gluten_free"]'
        ),

        # Timestamps
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment='Session creation timestamp (UTC)'
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            comment='Last session update timestamp (UTC)'
        ),
    )

    # Index on user_id for fast user session lookups
    op.create_index(
        'ix_chef_ai_sessions_user_id',
        'chef_ai_sessions',
        ['user_id'],
        unique=False
    )

    # Index on created_at for TTL-based cleanup queries
    op.create_index(
        'ix_chef_ai_sessions_created_at',
        'chef_ai_sessions',
        ['created_at'],
        unique=False
    )


def downgrade():
    op.drop_index('ix_chef_ai_sessions_created_at', table_name='chef_ai_sessions')
    op.drop_index('ix_chef_ai_sessions_user_id', table_name='chef_ai_sessions')
    op.drop_table('chef_ai_sessions')
